/**
 * Represents a single work experience entry stored in the database.
 */
export type WorkExperienceEntity = {
  /** Unique identifier */
  id: string;
  /** Company name */
  companyName: string;
  /** Job title */
  jobTitle: string;
  /** Workplace city location */
  workCityLocation: string;
  /** Job start date */
  startDate: Date;
  /** Job end date */
  endDate: Date;
  /** Job description */
  description: string;
};

/**
 * Payload used for creating a new work experience via API.
 * Omits the `id` field since it is generated by the database.
 * Changes the types for `startDate` and `endDate` fields because the API expects dates as strings.
 */
export type WorkExperiencePayload = Omit<
  WorkExperienceEntity,
  "id" | "startDate" | "endDate"
> & {
  startDate: string;
  endDate: string;
};
